version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 3gwine-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/app/prisma
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=https://ozketrcgjkqxwvynpxrd.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=sb_publishable_1rLZPddAjK_BqM0ruv2_fw_ULLTPI0B
      - PORT=3000
      - DATABASE_URL=file:/app/prisma/dev.db
    env_file:
      - .env
